[2018-12-23 20:08:21] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\bayle\\\\mon-projet-test\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":139,\"trace\":[{\"file\":\"C:\\\\Users\\\\bayle\\\\mon-projet-test\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-12-23 20:09:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\Users\bayle\mon-projet-test\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Matcher\\Dumper\\PhpMatcherTrait.php:176)"} []
[2018-12-23 20:09:07] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"a1478b"},"request_uri":"http://127.0.0.1:8000/_wdt/a1478b","method":"GET"} []
[2018-12-23 20:09:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://127.0.0.1:8000/")" at C:\Users\bayle\mon-projet-test\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://127.0.0.1:8000/\") at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Matcher\\Dumper\\PhpMatcherTrait.php:67)"} []
[2018-12-23 20:29:51] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")." at C:\Users\bayle\mon-projet-test\vendor\symfony\config\Loader\FileLoader.php line 166 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:29:52] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:29:52] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:29:52] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml").")." at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:29:52] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:29:53] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")." at C:\Users\bayle\mon-projet-test\vendor\symfony\config\Loader\FileLoader.php line 166 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:29:53] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:29:53] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:29:53] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml").")." at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:29:53] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:05] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")." at C:\Users\bayle\mon-projet-test\vendor\symfony\config\Loader\FileLoader.php line 166 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:05] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:05] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:05] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml").")." at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:05] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:06] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")." at C:\Users\bayle\mon-projet-test\vendor\symfony\config\Loader\FileLoader.php line 166 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:06] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:06] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:06] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml").")." at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:06] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:12] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")." at C:\Users\bayle\mon-projet-test\vendor\symfony\config\Loader\FileLoader.php line 166 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:12] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:12] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:12] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml").")." at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:12] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:13] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")." at C:\Users\bayle\mon-projet-test\vendor\symfony\config\Loader\FileLoader.php line 166 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:13] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:13] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:13] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml").")." at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-23 20:30:13] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-26 19:18:33] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")." at C:\Users\bayle\mon-projet-test\vendor\symfony\config\Loader\FileLoader.php line 166 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-26 19:18:36] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-26 19:18:36] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-26 19:18:36] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml").")." at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-26 19:18:36] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-26 19:18:37] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")." at C:\Users\bayle\mon-projet-test\vendor\symfony\config\Loader\FileLoader.php line 166 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-26 19:18:37] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-26 19:18:37] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-26 19:18:37] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml").")." at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-26 19:18:38] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The definition of "La_route_d_un_nombre_au_hasard" in "C:\Users\bayle\mon-projet-test\config/routes.yaml" must be a YAML array in C:\Users\bayle\mon-projet-test\config/routes.yaml (which is loaded in resource "C:\Users\bayle\mon-projet-test\config/routes.yaml")."). at C:\Users\bayle\mon-projet-test\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\").\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array in C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml (which is loaded in resource \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\"). at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\config\\Loader\\FileLoader.php:166, InvalidArgumentException(code: 0): The definition of \"La_route_d_un_nombre_au_hasard\" in \"C:\\Users\\bayle\\mon-projet-test\\config/routes.yaml\" must be a YAML array. at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Loader\\YamlFileLoader.php:250)"} []
[2018-12-26 19:23:45] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\Users\bayle\mon-projet-test\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Matcher\\Dumper\\PhpMatcherTrait.php:176)"} []
[2018-12-26 19:23:53] request.INFO: Matched route "La_route_d_un_nombre_au_hasard". {"route":"La_route_d_un_nombre_au_hasard","route_parameters":{"_route":"La_route_d_un_nombre_au_hasard","_controller":"App\\Controller\\nouvellepage::nombre"},"request_uri":"http://localhost:8000/UnNombreHasard","method":"GET"} []
[2018-12-26 19:23:53] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-12-26 19:23:55] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"0eff1e"},"request_uri":"http://127.0.0.1:8000/_wdt/0eff1e","method":"GET"} []
[2018-12-26 19:23:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://127.0.0.1:8000/")" at C:\Users\bayle\mon-projet-test\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://127.0.0.1:8000/\") at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Matcher\\Dumper\\PhpMatcherTrait.php:67)"} []
[2018-12-26 19:23:58] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f58ab6"},"request_uri":"http://localhost:8000/_wdt/f58ab6","method":"GET"} []
[2018-12-26 19:23:59] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8000/UnNombreHasard")" at C:\Users\bayle\mon-projet-test\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8000/UnNombreHasard\") at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\Users\\bayle\\mon-projet-test\\vendor\\symfony\\routing\\Matcher\\Dumper\\PhpMatcherTrait.php:67)"} []
[2018-12-26 19:24:08] request.INFO: Matched route "La_route_d_un_nombre_au_hasard". {"route":"La_route_d_un_nombre_au_hasard","route_parameters":{"_route":"La_route_d_un_nombre_au_hasard","_controller":"App\\Controller\\nouvellepage::nombre"},"request_uri":"http://localhost:8000/UnNombreHasard","method":"GET"} []
[2018-12-26 19:24:08] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-12-26 19:24:09] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"332246"},"request_uri":"http://localhost:8000/_wdt/332246","method":"GET"} []
[2018-12-26 19:24:20] request.INFO: Matched route "La_route_d_un_nombre_au_hasard". {"route":"La_route_d_un_nombre_au_hasard","route_parameters":{"_route":"La_route_d_un_nombre_au_hasard","_controller":"App\\Controller\\nouvellepage::nombre"},"request_uri":"http://localhost:8000/UnNombreHasard","method":"GET"} []
[2018-12-26 19:24:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-12-26 19:24:20] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"827737"},"request_uri":"http://localhost:8000/_wdt/827737","method":"GET"} []
[2018-12-26 19:24:23] request.INFO: Matched route "La_route_d_un_nombre_au_hasard". {"route":"La_route_d_un_nombre_au_hasard","route_parameters":{"_route":"La_route_d_un_nombre_au_hasard","_controller":"App\\Controller\\nouvellepage::nombre"},"request_uri":"http://localhost:8000/UnNombreHasard","method":"GET"} []
[2018-12-26 19:24:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-12-26 19:24:24] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"faa72a"},"request_uri":"http://localhost:8000/_wdt/faa72a","method":"GET"} []
